---
- name: Install Trivy vulnerability scanner
  hosts: localhost
  become: true
  tasks:
    - name: Download Trivy binary
      get_url:
        url: https://github.com/aquasecurity/trivy/releases/latest/download/trivy_0.50.1_Linux-64bit.tar.gz
        dest: /tmp/trivy.tar.gz

    - name: Extract Trivy
      unarchive:
        src: /tmp/trivy.tar.gz
        dest: /usr/local/bin/
        remote_src: yes
        extra_opts: [--strip-components=1]
        creates: /usr/local/bin/trivy

    - name: Ensure Trivy is executable
      file:
        path: /usr/local/bin/trivy
        mode: '0755'
        state: file
