---
- name: Export ROCm-SMI Configuration Checks to Prometheus Metrics
  hosts: localhost
  gather_facts: yes
  vars:
    metrics_dir: /var/lib/prometheus/node-exporter/textfile_collector
    metrics_file: "{{ metrics_dir }}/rocm_checks.prom"
    timestamp: "{{ ansible_date_time.epoch }}"

  tasks:
    - name: Ensure metrics directory exists
      file:
        path: "{{ metrics_dir }}"
        state: directory
        mode: '0755'
        owner: prometheus
        group: prometheus
      become: yes
      check_mode: no

    - name: Check if rocm-smi exists
      command: which rocm-smi
      register: rocm_smi_check
      ignore_errors: yes
      changed_when: false
      check_mode: no

    - name: Get ROCm-SMI version
      command: rocm-smi --version
      register: rocm_version
      when: rocm_smi_check.rc is defined and rocm_smi_check.rc == 0
      ignore_errors: yes
      changed_when: false
      check_mode: no

    - name: Get GPU information
      command: rocm-smi
      register: gpu_info
      when: rocm_smi_check.rc is defined and rocm_smi_check.rc == 0
      ignore_errors: yes
      changed_when: false
      check_mode: no

    - name: Prepare metrics content
      set_fact:
        metrics_content: |
          # HELP rocm_smi_installed Whether rocm-smi is installed (1=yes, 0=no)
          # TYPE rocm_smi_installed gauge
          rocm_smi_installed {{ '1' if rocm_smi_check.rc | default(2) == 0 else '0' }}
          
          # HELP rocm_smi_check_timestamp Unix timestamp of the last check
          # TYPE rocm_smi_check_timestamp gauge
          rocm_smi_check_timestamp {{ timestamp }}
          
          # HELP rocm_smi_gpu_available Whether GPU is detected by rocm-smi (1=yes, 0=no)
          # TYPE rocm_smi_gpu_available gauge
          rocm_smi_gpu_available {{ '1' if gpu_info.rc | default(2) == 0 else '0' }}
          
          # HELP rocm_smi_version_info ROCm-SMI version information
          # TYPE rocm_smi_version_info gauge
          rocm_smi_version_info{version="{{ rocm_version.stdout_lines[0] | default('unknown') | regex_replace('[^a-zA-Z0-9._-]', '_') }}" } 1

    - name: Write metrics to file
      copy:
        content: "{{ metrics_content }}"
        dest: "{{ metrics_file }}"
        mode: '0644'
        owner: prometheus
        group: prometheus
      become: yes
      check_mode: no

    - name: Display ROCm-SMI Status and Metrics Location
      debug:
        msg: |
          ROCm-SMI Status Summary:
          - Binary installed: {{ rocm_smi_check.rc | default(2) == 0 }}
          - Version info: {{ rocm_version.stdout_lines[0] | default('N/A') }}
          - GPU Available: {{ gpu_info.rc | default(2) == 0 }}
          
          {% if ansible_check_mode %}
          Running in CHECK MODE - no actual changes were made
          {% else %}
          Metrics have been written to: {{ metrics_file }}
          {% endif %}
